services:
  spark-master:
    build: ./spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8090:8080"
    environment:
      - SPARK_MODE=master

  spark-worker-1:
    build: ./spark
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

  jupyter:
    build: ./spark
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - spark-master
